matcher:
  KDTreeMatcher:
    knn: 8
    maxDist: 1
    epsilon: 1

outlierFilters:
 - VarTrimmedDistOutlierFilter:
    minRatio: 0.5
    maxRatio: 0.7
 - TimeOutlierFilter:

errorMinimizer:
  PointToPlaneErrorMinimizer:

transformationCheckers:
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 2
  - CounterTransformationChecker:
      maxIterationCount: 40
  - BoundTransformationChecker:
      maxRotationNorm: 1.1
      maxTranslationNorm: 15.0

inspector:
  VTKFileInspector:
    baseFileName: /home/sp/Desktop/debug_2/file
    dumpDataLinks: 1
    dumpReading: 1
    dumpReference: 1

logger:
  NullLogger
